## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [1]:
## import the pandas library in this cell

import pandas as pd

### Ingest the following dataset into this note:

In [2]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
import pandas as pd

dfbi = pd.read_csv("bridge-inspections-excerpt.csv")

dfbi

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [3]:
## call the first 10 rows

dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [4]:
## call the last 5 rows

dfbi.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [5]:
## call a 20 random rows

dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
9688,48,497,'Trib of Watson Branch',33184323.0,97374706.0,2.0,9.0,2011.0,4,2.0,7,7,6,6,N,NaN
94155,51,59,'RTE.50',38511175.0,77131364.0,NaN,1.0,2010.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
10081,48,77,'LODGE CREEK',33280677.0,98171612.0,1.0,8.0,1956.0,1,19.0,N,N,N,5,5,NaN
76604,50,7,'I189 UNDER US 7',44264922.0,73123380.0,NaN,11.0,1988.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
73865,50,3,'W. BR. DEERFIELD RIVER',42493355.0,73000871.0,3.0,9.0,1929.0,1,4.0,6,7,6,6,N,NaN
35026,48,453,'TRIB GILLELAND CREEK',30240422.0,97370702.0,4.0,19.0,2018.0,1,19.0,N,N,N,7,7,NaN
55514,48,479,'DRAINAGE DITCH',27322521.0,99300869.0,1.0,16.0,1962.0,1,19.0,N,N,N,6,6,NaN
85554,51,199,'CSX Railroad Spur',37000093.0,76242402.0,1.0,11.0,1983.0,4,2.0,6,6,6,8,N,NaN
8590,48,439,'TRIB TO KEE BRANCH',32391316.0,97111955.0,4.0,16.0,1999.0,1,19.0,N,N,N,7,6,NaN
17353,48,27,'DEER CRK #602',31144336.0,97151503.0,2.0,9.0,1994.0,1,2.0,7,7,7,5,N,NaN
81530,51,97,'HEARTQUAKE CREEK',37380384.0,76491791.0,1.0,6.0,1952.0,1,4.0,5,5,6,5,N,NaN
80754,51,79,'Swift Run',38180999.0,78293050.0,1.0,9.0,1982.0,3,2.0,5,5,7,6,N,1.0
91903,51,89,'RTE 220',36414318.0,79571331.0,NaN,2.0,1976.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
46286,48,113,'IH 635 TXE WB & OFF-RAMP',32551068.0,96511045.0,1.0,11.0,2014.0,5,2.0,7,7,7,N,N,NaN
30139,48,123,'DRAW',29062151.0,97285217.0,2.0,9.0,2015.0,3,2.0,7,7,7,6,N,NaN
75896,50,25,'EAST PUTNEY BROOK',43000111.0,72291954.0,1.0,7.0,1986.0,1,19.0,N,N,N,8,8,NaN
71455,49,53,'SR-7 SOUTHERN PARKWAY',37005255.0,113293937.0,1.0,17.0,2010.0,5,2.0,7,8,6,N,N,NaN
75892,50,25,'FALL RIVER',42450069.0,72341046.0,1.0,7.0,1939.0,1,4.0,6,6,7,8,N,NaN
84264,51,173,'R658 SCRATCH GRAVEL RD.',36492299.0,81305978.0,1.0,11.0,1962.0,4,2.0,7,7,7,7,N,NaN
56800,48,281,'DRAW',31101718.0,98045774.0,1.0,7.0,1960.0,1,19.0,N,N,N,6,7,NaN

In [6]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

dfbi.info()

## there are strings, integers and floats
## 16 columns, 100_000 rows

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate?

## Column 15, pier protection, missing about 85K cells

In [8]:
## call the top 7 rows

dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [9]:
## call a sample of 10

dfbi.sample(18)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
49701,48,139,'E FORK CHAMBERS CREEK',32185360.0,97022573.0,2.0,9.0,1991.0,3,2.0,7,6,5,6,N,NaN
17709,48,99,'TRIB LEON RIVER',31314084.0,97471056.0,1.0,6.0,1955.0,1,19.0,N,N,N,7,7,NaN
26931,48,201,'HARDY RD & UP RR YARD',30042430.0,95245843.0,2.0,16.0,1989.0,5,2.0,6,7,6,N,N,NaN
48274,48,121,'IH 35W',33044711.0,97140809.0,1.0,9.0,1969.0,4,2.0,7,6,7,N,N,NaN
5716,48,221,'LAMBERT BRANCH',32263354.0,97463806.0,1.0,16.0,1968.0,1,2.0,6,6,5,7,N,1.0
14617,48,399,'DRAW',32005259.0,100011834.0,2.0,9.0,1930.0,4,2.0,5,6,5,6,N,NaN
17463,48,27,'S NOLAN CRK #109',31043612.0,97313946.0,2.0,9.0,2004.0,5,2.0,7,7,7,7,N,NaN
22032,48,347,'LA NANA BAYOU',31425375.0,94372640.0,2.0,9.0,2001.0,4,2.0,7,6,6,5,N,NaN
8518,48,439,'Trib Johnson Creek',32432336.0,97053378.0,4.0,19.0,1975.0,1,19.0,N,N,N,7,7,NaN
77701,51,15,'WET WEATHER TRIB S RIVER',38110852.0,78502962.0,1.0,6.0,1942.0,1,4.0,5,5,6,5,N,NaN
79731,51,59,'PIKE BRANCH',38473593.0,77050091.0,1.0,16.0,1960.0,1,19.0,N,N,N,5,6,NaN
15197,48,59,'FM 2228',32230960.0,99175468.0,1.0,1.0,1965.0,2,1.0,7,7,7,N,N,NaN
98581,53,25,'SADDLE MOUNTAIN WASTEWAY',46434620.0,119444710.0,2.0,8.0,1969.0,5,22.0,7,7,7,7,N,NaN
41678,48,391,'DRY CREEK',28173996.0,97154917.0,1.0,7.0,2007.0,5,0.0,7,8,8,7,N,NaN
38314,48,29,'SAN ANTONIO RIVER',29252320.0,98291632.0,4.0,14.0,1926.0,2,4.0,6,7,7,8,N,NaN
12306,48,303,'YELLOW HOUSE DRAW',33361319.0,101511036.0,1.0,17.0,1955.0,1,19.0,N,N,N,7,6,1.0
32662,48,55,'WOLF CREEK',29390141.0,97352661.0,1.0,2.0,1972.0,1,19.0,N,N,N,6,7,NaN
60635,48,439,'SH-360',32473611.0,97032411.0,NaN,12.0,1986.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
## call the bottom 6

dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [11]:
## call the year built column using dot notation

dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [12]:
## call FEATURES_DESC_006A as a series using square bracket notation

dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [14]:
## what are the unique owner codes?

dfbi.OWNER_022.unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

## Each code represents a different owner